[project]
name = "djiapp"
version = "0.1.0"
description = "WebApp para análisis de vuelos DJI"
authors = ["Your Name <you@example.com>"]
requires-python = ">=3.11"

dependencies = [
    "flask",
    "watchdog",
    "pandas"
]

[tool.pdm]